### ISSUE TITLE
Create branch compatible with Modelon Impact v1.8.0

### ISSUE THREAD

**Issue by lewismc** [Open-MBEE/perseverance-modelica#9]
The [dependencies defined in .impact/project.json](https://github.com/Open-MBEE/perseverance-modelica/blob/main/.impact/project.json) are incompatible with older versions of Modelon Impact, namely 1.8.0.

I propose to create a branch such that users still on the older v1.8.0 can still work with this example.

**Comment by psundstrom** [comment]
Hi,

I created a branch **vdl-4.1** that should work with Impact 1.8.0.

**Comment by lewismc** [comment]
Hi @psundstrom excellent, thank you. I have a couple of requests

1. It would be greatly appreciated if you could tag and release the branch such that it is totally clear as to the version of Modelon Impact that the model is interoperable with. Thank you
2. When future changes are made to the models, it would be fantastic if we could also tag and release them and clearly identify which version of Modelon Impact they work with. Thank you very much 👍 

We are testing the branch right now.

**Comment by lewismc** [comment]
Hi @psundstrom , OK I'm glad to verify that the `vdl-4.1` branch is indeed compatible with Modelon Impact v1.8.0 :) Fantastic.
I'll go ahead and close off this issue. Thank you
